name: mybooks
description: My books
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: 0.17.0
  cupertino_icons: ^1.0.4
  provider: ^6.0.2
  shared_preferences: ^2.0.13
  flutter_svg: ^1.0.3
  rxdart: ^0.27.3
  dio: ^4.0.4
  built_value: ^8.1.4
  cached_network_image: ^3.2.0
  path_provider: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_lints: ^1.0.4
  intl_generator: ^0.2.1
  build_runner: ^2.1.7
  built_value_generator: ^8.1.4

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: SFProDisplay
      fonts:
        - asset: fonts/SF-Pro-Display-Medium.otf
          weight: 500
        - asset: fonts/SF-Pro-Display-Semibold.otf
          weight: 600
    - family: SFProText
      fonts:
        - asset: fonts/SF-Pro-Text-Regular.otf
        - asset: fonts/SF-Pro-Text-Semibold.otf
          weight: 600
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Medium.ttf
          weight: 500